server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.69.46.151:3306/face?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: nzd8712866

mybatis:
  mapper-locations: classpath*:mapper/*.xml

minio:
  endpoint: http://81.69.46.151:9000
  accessKey: minio
  secretKey: nzd8712866

face:
  appId: DeS2sG7SjSpAypwaMbLMi2HCmj3zmr96dET2nTwNZ3Sy
  sdkKey: CMmZzs5RtDLttzbSRkBJvysiLxJyM2AWmvQrftw5yENU
  activeKey: 082Y-1143-W14Y-18U9
  activeFile:

milvus:
  host: 81.69.46.151
  port: 9000
