server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.69.46.151:3306/face?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: nzd8712866

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

minio:
  endpoint: http://81.69.46.151:9000
  accessKey: minio
  secretKey: nzd8712866

face:
  appId: DeS2sG7SjSpAypwaMbLMi2HKw8KEP2YhahJEGUZaywoT
  sdkKey: D5pgPpJC4js7TL59wY1eqaTV6JCDHpPc2pnVPB9LKM94
  activeKey: 86C1-116L-L13F-5V6P
  activeFile:

milvus:
  host: 81.69.46.151
  port: 19530
  collectionName: face
